apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: svc-gateway
  name: svc-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: svc-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: svc-gateway
    spec:
      containers:
        - env:
            - name: ORDER_SERVICE_URL
              value: http://svc-order:8002/order/create
            - name: USER_SERVICE_URL
              value: http://svc-user:8001/user/info
          image: svc-gateway
          name: svc-gateway
          ports:
            - containerPort: 8003
              protocol: TCP
      restartPolicy: Always
